// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	Admin "Final_Project/business/Admin"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *Repository) Login(ctx context.Context, username string, password string) (Admin.DomainAdmin, error) {
	ret := _m.Called(ctx, username, password)

	var r0 Admin.DomainAdmin
	if rf, ok := ret.Get(0).(func(context.Context, string, string) Admin.DomainAdmin); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(Admin.DomainAdmin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
